jasypt:
  encryptor:
    bean: encryptorBean
    algorithm: PBEWITHHMACSHA512ANDAES_256
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

secret2:
  property: ENC(VsW0IMmYs2hbQJMVcpxp8eZxFyvuAg4wRQaIwv5sT4hL0SuwVq38SlSLPz8SEORy)
