jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    property:
      prefix: "ENC@["
      suffix: "]"
secret2:
  property: ENC@[IPrhI5r+NjLceWC5r1J+YjJeOYkSInbDmfnUQ+h6OgqOoIGRq37nh1/HwPoloGwW]
