jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD:}

user2: uli
defaultPassword2: ENC(nrmZtkF7T0kjG/VodDvBw93Ct8EgjCA+)
# works with @EnableEncryptableProperties and StandardEncryptableEnvironment
endpoint2: https://${user2}:${defaultPassword2}@localhost:30000

